CHGPFM FILE(RUTUTORIAL) MBR(ORDERS)   SRCTYPE(PF) TEXT('RPGUnit Example - Order file.')
CHGPFM FILE(RUTUTORIAL) MBR(CUSTSUMS) SRCTYPE(PF) TEXT('RPGUnit Example - Customer Totals file.')
CRTPF FILE(ORDERS)   SRCFILE(RUTUTORIAL)
CRTPF FILE(CUSTSUMS) SRCFILE(RUTUTORIAL)
